apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: nicktsioutsias/starter:0.0.1
          ports:
            - name: http
              containerPort: 80  

---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: app
spec:
  selector:
    app: my-app
  ports:
    - name: http
      protocol: TCP
      port: 80       
      targetPort: 80
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service-ext
  namespace: app
spec:
  selector:
    app: my-app
  ports:
    - name: http
      protocol: TCP
      port: 80  
  type: NodePort