FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY memoryForecastApp.py .
COPY memory_model.pkl .

EXPOSE 8500

CMD ["uvicorn", "memoryForecastApp:app", "--host", "0.0.0.0", "--port", "8500"]